name: Node.js CI

on:
  push:
    branches: ["dev"]

jobs:
  build:
    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [18.19.1]

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"

      - name: Create .env file
        run: |
          touch .env
          echo DATABASE_URL=${{ secrets.DATABASE_URL }} >> .env
          echo PORT=${{ secrets.PORT }} >> .env
          echo CLOUDINARY_NAME=${{ secrets.CLOUDINARY_NAME }} >> .env
          echo CLOUDINARY_API_KEY=${{ secrets.CLOUDINARY_API_KEY }} >> .env
          echo CLOUDINARY_API_SECRET=${{ secrets.CLOUDINARY_API_SECRET }} >> .env
          echo project_id=${{ secrets.project_id }} >> .env
          echo PRIVATE_KEY="${{ secrets.PRIVATE_KEY }}" >> .env
          echo CLIENT_EMAIL=${{ secrets.CLIENT_EMAIL }} >> .env
          echo JWT_SECRET=${{ secrets.JWT_SECRET }} >> .env
          cat .env

      - run: npm ci
      - run: npm run build --if-present
